<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit20e7125377fd77c535da3a2ab94b47ac
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit20e7125377fd77c535da3a2ab94b47ac::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit20e7125377fd77c535da3a2ab94b47ac::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
